version: '3.1'
services:
  upload-service:
    build: upload/upload-server
    image: upload-server
    container_name: upload-server
    ports:
      - "9090:9090"
    environment:
      - BUCKET_NAME=your_bucket
      - ACCESS_KEY_ID=your_key
      - SECRET_KEY=your_secret

  s3-service:
    build: main
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - main-db
    environment:
      - UPLOAD_SERVER_URL=http://upload-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/s3-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  main-db:
    image: postgres:14-alpine
    container_name: main-db
    ports:
      - "6551:5432"
    environment:
      - POSTGRES_DB=s3-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - TZ=GMT

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
